# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\recognition.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal, pyqtSlot, Qt, QObject, QThread
from PyQt5.QtGui import QPixmap, QImage, QColor
from matplotlib.backends.qt_compat import QtCore, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvas
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.figure as mpl_fig
import matplotlib.animation as anim
import numpy as np
import random
import qdarkstyle
import cv2
import sys
import os


this_dir = os.path.dirname(os.path.realpath(__file__))


class ImageWidget(QtWidgets.QLabel):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setScaledContents(True)

    def hasHeightForWidth(self):
        return self.pixmap() is not None

    def heightForWidth(self, w):
        if self.pixmap():
            return int(w * (self.pixmap().height() / self.pixmap().width()))


class MyFigureCanvas(FigureCanvas):
    '''
    This is the FigureCanvas in which the live plot is drawn.

    '''

    def __init__(self, parent=None):
        plt.style.use('dark_background')
        FigureCanvas.__init__(self, mpl_fig.Figure())

        # Range settings
        self.x_len = 56
        self.y_range = [0, 1]

        x = list(range(0, self.x_len))
        y = [0] * self.x_len

        # Store a figure and ax
        self.ax = self.figure.subplots()
        self.ax.set_title("Last CNN's layer output")
        self.ax.set_ylim(ymin=self.y_range[0], ymax=self.y_range[1])
        self.rects = self.ax.bar(x, y)

    def update_canvas(self, y, max_index):
        for rect, h in zip(self.rects, y):
            rect.set_height(h)
            rect.set_color('white')
        self.rects[max_index].set_color('red')
        self.figure.canvas.draw()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(964, 811)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.video_frame = QtWidgets.QFrame(self.centralwidget)
        self.video_frame.setGeometry(QtCore.QRect(9, 9, 611, 461))
        self.video_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.video_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.video_frame.setObjectName("video_frame")

        self.camera_video = QtWidgets.QLabel(self.video_frame)
        self.camera_video.setGeometry(QtCore.QRect(4, 5, 601, 451))
        self.camera_video.setObjectName("camera_video")

        self.result_frame = QtWidgets.QFrame(self.centralwidget)
        self.result_frame.setGeometry(QtCore.QRect(639, 9, 301, 371))
        self.result_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.result_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.result_frame.setObjectName("result_frame")

        self.result_image = ImageWidget(self.result_frame)
        self.result_image.setGeometry(QtCore.QRect(0, 0, 301, 371))
        self.result_image.setFrameShape(QtWidgets.QFrame.Box)
        self.result_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.result_image.setObjectName("result_image")

        self.graph_frame = QtWidgets.QFrame(self.centralwidget)
        self.graph_frame.setGeometry(QtCore.QRect(9, 479, 941, 271))
        self.graph_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.graph_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.graph_frame.setObjectName("graph_frame")

        self.graph = MyFigureCanvas()
        self.lyt = QtWidgets.QVBoxLayout()
        self.graph_frame.setLayout(self.lyt)
        self.lyt.addWidget(self.graph)

        self.confidence_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.confidence_bar.setGeometry(QtCore.QRect(640, 430, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        self.confidence_bar.setFont(font)
        self.confidence_bar.setProperty("value", 0)
        self.confidence_bar.setObjectName("confidence_bar")
        self.confidence_text = QtWidgets.QLabel(self.centralwidget)
        self.confidence_text.setGeometry(QtCore.QRect(650, 390, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        self.confidence_text.setFont(font)
        self.confidence_text.setObjectName("confidence_text")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 964, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStop_recognition = QtWidgets.QAction(MainWindow)
        self.actionStop_recognition.setObjectName("actionStop_recognition")
        self.actionStart_recognition = QtWidgets.QAction(MainWindow)
        self.actionStart_recognition.setObjectName("actionStart_recognition")
        self.actionStop_graph = QtWidgets.QAction(MainWindow)
        self.actionStop_graph.setObjectName("actionStop_graph")
        self.actionStart_graph = QtWidgets.QAction(MainWindow)
        self.actionStart_graph.setObjectName("actionStart_graph")
        self.menuMenu.addAction(self.actionStop_recognition)
        self.menuMenu.addAction(self.actionStart_recognition)
        self.menuMenu.addAction(self.actionStop_graph)
        self.menuMenu.addAction(self.actionStart_graph)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        # self.camera_video.setText(_translate("MainWindow", "TextLabel"))
        self.confidence_text.setText(_translate("MainWindow", "Confidence"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionStop_recognition.setText(
            _translate("MainWindow", "Stop recognition"))
        self.actionStart_recognition.setText(
            _translate("MainWindow", "Start recognition"))
        self.actionStop_graph.setText(_translate("MainWindow", "Stop graph"))
        self.actionStart_graph.setText(_translate("MainWindow", "Start graph"))
